
# Gem::Specification for Nfoiled-0
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: Nfoiled
version: !ruby/object:Gem::Version 
  version: "0"
platform: ruby
authors: 
- elliottcable
autorequire: 
bindir: bin

date: 2008-09-22 00:00:00 -08:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: ncurses
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: rspec
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: rcov
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: yard
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: stringray
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: The Rubyist's interface to Ncurses.
email: 
- Nfoiled@elliottcable.com
executables: []

extensions: []

extra_rdoc_files: 
- lib/nfoiled.rb
- LICENSE.text
- README.markdown
files: 
- lib/nfoiled.rb
- LICENSE.text
- Rakefile.rb
- README.markdown
- spec/nfoiled_spec.rb
- spec/spec_helper.rb
- .manifest
- nfoiled.gemspec
has_rdoc: true
homepage: http://github.com/elliottcable/nfoiled
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Nfoiled
- --main
- README.markdown
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: nfoiled
rubygems_version: 1.2.0
specification_version: 2
summary: The Rubyist's interface to Ncurses.
test_files: []
